### ISSUE TITLE
Award chains / levels

### ISSUE THREAD

**Issue by rubenwardy** [rubenwardy/awards#53]
From #52 

> @numberZero
> That sounds more like “multi-level” award. As in some modern games, where you can complete a level with different rating (e.g. 1 to 3 stars).

> @rubenwardy
> Yeah, I'm wondering whether this should actually be displayed in one award as a rating, and the progress to the next rating. So say 1 and 2 are unlocked, all you would see is 2 in the list with a progress bar towards 3.

**Comment by numberZero** [comment]
For straightforward progress, yes, that should be a rating inside the award. (Ratings might be labelled with some MT resources, like bronze, gold, diamonds =) e.g. they may correspond to tool levels, wood→stone→iron→bronze→mese→diamond)
