### ISSUE TITLE
Improve sorting algorithm

### ISSUE THREAD

**Issue by rubenwardy** [rubenwardy/awards#56]
Currently it sorts based on target number and percentage progress. This isn't good when it comes to more difficult things - for example, crafting 3 torches should be sorted before digging 1 nyancat / diamond

How can the difficultness of an award be calculated? Should it just use a new awards definition member "difficulty"

**Comment by bell07** [comment]
I think the "difficulty" setting is the right way. I do not see a way to calculate the challenges chance automatically. The "difficulty" should be a multiplier, so if the "dig 1 nyancat" have difficulty 100, it is shown on the same level as "craft 100 torches" with difficulty 1.
The default difficulty should not be 1 but 10(?) to be able to define "easy things" shown above.

PS: What is with idea to add timestamp and sort already reached awards by timestamp? You just closed the #28 Still think it is the right way, the player can see his progress in a timeline this way

**Comment by rubenwardy** [comment]
Added difficulty multipler: f005238
