### ISSUE TITLE
crashes caused by mod pipeworks

### ISSUE THREAD

**Issue by heavygale** [rubenwardy/awards#60]
----

> ServerError: AsyncErr: environment_Step: Runtime error from mod 'awards' in callback environment_Step():
> [...mods/awards/awards.lua:231](https://github.com/rubenwardy/awards/blob/master/awards.lua#L231): attempt to call method 'get_pos' (a nil value)
> 
> stack traceback:
>     ...mods/awards/awards.lua:231: in function 'entry'
>     ...mods/awards/api.lua:111: in function 'run_callbacks'
>     ...mods/awards/api.lua:232: in function 'notify_dig'
>     ...mods/awards/triggers.lua:76: in function 'callback'
>     ...builtin/game/item.lua:631: in function 'on_dig'
>     [...mods/pipeworks/wielder.lua:392](https://github.com/minetest-mods/pipeworks/blob/master/wielder.lua#L392): in function 'act'
>     ...mods/pipeworks/wielder.lua:167: in function 'wielder_on'
>     ...mods/pipeworks/wielder.lua:203: in function 'action_on'
>     ...mods/mesecons/mesecons/internal.lua:190: in function <...mods/mesecons/mesecons/internal.lua:183>
>     ...mods/mesecons/mesecons/actionqueue.lua:93: in function 'execute'
>     ...mods/mesecons/mesecons/actionqueue.lua:84: in function <...mods/mesecons/mesecons/actionqueue.lua:61>
>     ...builtin/game/register.lua:420: in function <...builtin/game/register.lua:400>

----

> ServerError: AsyncErr: environment_Step: Runtime error from mod '' in callback environment_Step():
> [...mods/awards/api.lua:422](https://github.com/rubenwardy/awards/blob/master/api.lua#L422): attempt to index local 'player' (a nil value)
> 
> stack traceback:
>     ...mods/awards/api.lua:422: in function 'unlock'
>     ...mods/awards/api.lua:117: in function 'run_callbacks'
>     ...mods/awards/api.lua:232: in function 'notify_place'
>     ...mods/awards/triggers.lua:96: in function 'callback'
>     ...games/minetest_game/mods/default/trees.lua:551: in function 'sapling_on_place'
>     ...games/minetest_game/mods/default/nodes.lua:646: in function 'on_place'
>     [...mods/pipeworks/wielder.lua:463](https://github.com/minetest-mods/pipeworks/blob/master/wielder.lua#L463): in function 'act'
>     ...mods/pipeworks/wielder.lua:167: in function 'wielder_on'
>     ...mods/pipeworks/wielder.lua:203: in function 'action_on'
>     ...mods/mesecons/mesecons/internal.lua:190: in function <...mods/mesecons/mesecons/internal.lua:183>
>     ...mods/mesecons/mesecons/actionqueue.lua:93: in function 'execute'
>     ...mods/mesecons/mesecons/actionqueue.lua:84: in function <...mods/mesecons/mesecons/actionqueue.lua:61>
>     ...builtin/game/register.lua:420: in function <...builtin/game/register.lua:400>

----

**Comment by SmallJoker** [comment]
Fixed in pipeworks. Can be closed now.
